// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: noval.proto

package com.yc.proto;

public final class noval {
  private noval() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yc_proto_StreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yc_proto_StreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yc_proto_StreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yc_proto_StreamResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yc_proto_StudentResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yc_proto_StudentResponseList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yc_proto_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yc_proto_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yc_proto_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yc_proto_StudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yc_proto_NovalRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yc_proto_NovalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yc_proto_NovalReponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yc_proto_NovalReponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013noval.proto\022\014com.yc.proto\"%\n\rStreamReq" +
      "uest\022\024\n\014request_info\030\001 \001(\t\"\'\n\016StreamResp" +
      "onse\022\025\n\rresponse_info\030\001 \001(\t\"M\n\023StudentRe" +
      "sponseList\0226\n\017studentResponse\030\001 \003(\0132\035.co" +
      "m.yc.proto.StudentResponse\"\035\n\016StudentReq" +
      "uest\022\013\n\003age\030\001 \001(\005\":\n\017StudentResponse\022\014\n\004" +
      "name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\014\n\004city\030\003 \001(\t\"S\n" +
      "\014NovalRequest\022\n\n\002id\030\001 \001(\005\022\021\n\tnovalName\030\002" +
      " \001(\t\022\023\n\013chapterName\030\003 \001(\t\022\017\n\007content\030\004 \001" +
      "(\t\"Z\n\014NovalReponse\022\n\n\002id\030\001 \001(\005\022\021\n\tnovalN",
      "ame\030\002 \001(\t\022\023\n\013chapterName\030\003 \001(\t\022\026\n\016chapte" +
      "rContent\030\004 \001(\t2\352\002\n\014NovalService\022M\n\021getNo" +
      "valByChapter\022\032.com.yc.proto.NovalRequest" +
      "\032\032.com.yc.proto.NovalReponse\"\000\022S\n\020getStu" +
      "dentsByAge\022\034.com.yc.proto.StudentRequest" +
      "\032\035.com.yc.proto.StudentResponse\"\0000\001\022\\\n\025g" +
      "etStudentByAgeStream\022\034.com.yc.proto.Stud" +
      "entRequest\032!.com.yc.proto.StudentRespons" +
      "eList\"\000(\001\022X\n\025sendAndReceiveMessage\022\033.com" +
      ".yc.proto.StreamRequest\032\034.com.yc.proto.S",
      "treamResponse\"\000(\0010\001B\027\n\014com.yc.protoB\005nov" +
      "alP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_yc_proto_StreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_yc_proto_StreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yc_proto_StreamRequest_descriptor,
        new String[] { "RequestInfo", });
    internal_static_com_yc_proto_StreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_yc_proto_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yc_proto_StreamResponse_descriptor,
        new String[] { "ResponseInfo", });
    internal_static_com_yc_proto_StudentResponseList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_yc_proto_StudentResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yc_proto_StudentResponseList_descriptor,
        new String[] { "StudentResponse", });
    internal_static_com_yc_proto_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_yc_proto_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yc_proto_StudentRequest_descriptor,
        new String[] { "Age", });
    internal_static_com_yc_proto_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_yc_proto_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yc_proto_StudentResponse_descriptor,
        new String[] { "Name", "Age", "City", });
    internal_static_com_yc_proto_NovalRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_yc_proto_NovalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yc_proto_NovalRequest_descriptor,
        new String[] { "Id", "NovalName", "ChapterName", "Content", });
    internal_static_com_yc_proto_NovalReponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_yc_proto_NovalReponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yc_proto_NovalReponse_descriptor,
        new String[] { "Id", "NovalName", "ChapterName", "ChapterContent", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
