// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: noval.proto

package com.yc.proto;

public interface NovalRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.yc.proto.NovalRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string novalName = 2;</code>
   */
  String getNovalName();
  /**
   * <code>string novalName = 2;</code>
   */
  com.google.protobuf.ByteString
      getNovalNameBytes();

  /**
   * <code>string chapterName = 3;</code>
   */
  String getChapterName();
  /**
   * <code>string chapterName = 3;</code>
   */
  com.google.protobuf.ByteString
      getChapterNameBytes();

  /**
   * <code>string content = 4;</code>
   */
  String getContent();
  /**
   * <code>string content = 4;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
