// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: noval.proto

package com.yc.proto;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.yc.proto.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.yc.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<StudentResponse>
      getStudentResponseList();
  /**
   * <code>repeated .com.yc.proto.StudentResponse studentResponse = 1;</code>
   */
  StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .com.yc.proto.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .com.yc.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends com.yc.proto.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .com.yc.proto.StudentResponse studentResponse = 1;</code>
   */
  com.yc.proto.StudentResponseOrBuilder getStudentResponseOrBuilder(
          int index);
}
